name: fav_places_udemy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.3
  http: ^1.1.2
  image_picker: ^1.0.5
  location: ^5.0.3
  path: ^1.8.3
  path_provider: ^2.1.2
  riverpod_annotation: ^2.3.3
  sqflite: ^2.3.0
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
